FROM ubuntu:latest

RUN mkdir -p /opt/crawl3r

COPY ./ /opt/crawl3r

WORKDIR /opt/crawl3r

RUN 	apt update && \
	apt  install -y python3.8 && \
	apt  install -y python3-pip && \
	pip3 install -r requirements.txt

RUN chmod +x crawl3r.py

ENTRYPOINT ["./crawl3r.py"]
